remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: [Tianrui (Orlando) Fang]
description: [University of Michigan - Ann Arbor Undergraduate Junior Majoring in Computer Science]
